spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pismodb
    username: pismo
    password: p15m0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          use_streams_for_binary: true
          time_zone: UTC

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-doc.html
